# Generated by Django 5.2.1 on 2025-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
