# Generated by Django 5.2.1 on 2025-06-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo', '0003_task_done'),
    ]

    operations = [
    ]
